stages:
  - build

include:
  - project: 'hive/common-ci-configuration'
    ref: develop
    file: '/templates/docker_image_jobs.gitlab-ci.yml'

build:
  extends: .docker_build_job_template
  stage: build
