stages:
  - test
  - build

include:
  - project: 'hive/common-ci-configuration'
    ref: develop
    file: '/templates/docker_image_jobs.gitlab-ci.yml'

test:
  stage: test
  image: registry.gitlab.syncad.com/hive/imagehoster/node:20-alpine
  before_script:
    - apk add --no-cache bash build-base fftw-dev git make py-pip vips-dev
    - yarn install --non-interactive --frozen-lockfile
  script:
    - make lib ci-test
  artifacts:
    when: always
    reports:
      junit: reports/unit-tests/junit.xml
    paths:
      - reports/

build:
  extends: .docker_build_job_template
  stage: build
